version: '3.4'

services:
  familytreedb:
    container_name: "family-tree-db"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
  familytreeapi:
    container_name: "family-tree-api"
    image: "familytreeapi:development"
    ports:
      - "3000:3000" 
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Deployment
      - ASPNETCORE_URLS=http://*:3000
    depends_on:
      - familytreedb
